version: '3.3'
services:
  myDb:  
    image: mysql:5.7
    container_name: myDb
    restart: always
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_USER: product
      MYSQL_PASSWORD: product@123
      MYSQL_ROOT_PASSWORD: root@123
    ports:
       - "3306:3306"
    volumes:
      - data:/var/lib/mysql/productdata  
  productservice:
    image: vinisalgaonkar/productservice:latest
    container_name: productservice
    ports:
      - "9000:9000"
    depends_on:
      - myDb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://myDb:3306/inventory?useSSL=false   
      - SPRING_DATASOURCE_USERNAME=product
      - SPRING_DATASOURCE_PASSWORD=product@123
  myDb:  
    image: mysql:5.7
    container_name: customerDb
    restart: always
    environment:
      MYSQL_DATABASE: customer
      MYSQL_USER: customer
      MYSQL_PASSWORD: customer@123
      MYSQL_ROOT_PASSWORD: root@123
    ports:
       - "3306:3307"
    volumes:
      - customerdata:/var/lib/mysql/customerdata        
  customerservice:
    image: vinisalgaonkar/customerservice:latest
    container_name: customerservice
    ports:
      - "9001:9001"
    depends_on:
      - cusotmerDb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://customerDb:3307/customer?useSSL=false   
      - SPRING_DATASOURCE_USERNAME=customer
      - SPRING_DATASOURCE_PASSWORD=customer@123
  sampleui:
    image: sampleui:latest
    container_name : sampleui
    ports:
      - '3000:3000'
    links:
      - productservice
      - customerservice
volumes:
  data:
    name: data